In [1]:
""" Class 12. Ensemble Learning """

import os
import pandas as pd

In [2]:
""" Machine Learning Foundational Concepts: A Review 

Three major section of machine learning workflow.
1. Data (Prepare data for training)
   1.1. Data Collection
   1.2. Data Loading
   1.3. Data Cleaning
   1.4. Data Exploration and Visualization
   1.5. Feature Engineering: Feature Selection + Feature Transformation
   1.6. Data Splitting: Train-Test-Validation fairly
2. Model: 
   2.1. Machine Learning Algorithm
   2.2. Artificial Neural Network
   2.3. AI Algorithm i.e. Genetic Algorithm
3. Training
   Hyperparameters tuning i.e. epochs, learning rate, batch size, regularizer etc.
   Optimizer i.e Gradient Descent Based. Most popular: Adam Optimizer
   Compute Gradient i.e. Gradient Computation Graph 
   Update parameters
   
Overfitting, Underfitting, Generalization

Overfitting: Model's performance very good on training data but poor on test data
             Reasons: Model is too big / complex than training data
                      Or dataset is too small
            Solution: Regularization - Adds penalty
                      Ensemble Learning i.e Hybrid - Prediction is done by more than one algorithms
                      Dropout - Removes some connection from the ANN
Underfitting: Model's performance is poor on training and testing
              Reasons: Model is too simple to capture the underlying data distribution
              Solution: Select more complex model or algorithm
Generalization (Ideal case): Model's performance is well balanced in both training and testing
"""

print("Machine Learning Foundational Concepts: A Review")

Machine Learning Foundational Concepts: A Review

# Data

In [3]:
"""
Objectives:
1. Understand three classification algorithm
   1.1. Decision Tree
   1.2. K-Nearest Neighbour
   1.3. Support Vector Machine 
2. How to generalize your model
   2.1. Regularization
   2.2. Ensemble Learning (Bagging, Boosting, Stacking, Voting)
3. How to Scikit Learn for Machine Learning
"""

ROOT_DIR = "E:\\PyCharmProjects\\pythonProject"
DATA_DIR = os.path.join(ROOT_DIR, "data")
DATASET_PATH = os.path.join(DATA_DIR, "housing.csv")

dataset = pd.read_csv(DATASET_PATH)
dataset.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [4]:
dataset.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [5]:
numerical_cols = dataset.select_dtypes(include='number').columns
categorical_cols = dataset.select_dtypes(include='object').columns

print(numerical_cols)
print(categorical_cols)

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'parking'], dtype='object')
Index(['mainroad', 'guestroom', 'basement', 'hotwaterheating',
       'airconditioning', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [6]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

scaler = StandardScaler()
label_encoder = LabelEncoder()

In [7]:
dataset[numerical_cols] = scaler.fit_transform(dataset[numerical_cols])
dataset[numerical_cols]

        price      area  bedrooms  bathrooms   stories   parking
0    4.566365  1.046726  1.403419   1.421812  1.378217  1.517692
1    4.004484  1.757010  1.403419   5.405809  2.532024  2.679409
2    4.004484  2.218232  0.047278   1.421812  0.224410  1.517692
3    3.985755  1.083624  1.403419   1.421812  0.224410  2.679409
4    3.554979  1.046726  1.403419  -0.570187  0.224410  1.517692
..        ...       ...       ...        ...       ...       ...
540 -1.576868 -0.991879 -1.308863  -0.570187 -0.929397  1.517692
541 -1.605149 -1.268613  0.047278  -0.570187 -0.929397 -0.805741
542 -1.614327 -0.705921 -1.308863  -0.570187 -0.929397 -0.805741
543 -1.614327 -1.033389  0.047278  -0.570187 -0.929397 -0.805741
544 -1.614327 -0.599839  0.047278  -0.570187  0.224410 -0.805741

[545 rows x 6 columns]

In [8]:
dataset[categorical_cols] = dataset[categorical_cols].apply(label_encoder.fit_transform)
dataset.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,4.566365,1.046726,1.403419,1.421812,1.378217,1,0,0,0,1,1.517692,1,0
1,4.004484,1.757010,1.403419,5.405809,2.532024,1,0,0,0,1,2.679409,0,0
2,4.004484,2.218232,0.047278,1.421812,0.224410,1,0,1,0,0,1.517692,1,1
3,3.985755,1.083624,1.403419,1.421812,0.224410,1,0,1,0,1,2.679409,1,0
4,3.554979,1.046726,1.403419,-0.570187,0.224410,1,1,1,0,1,1.517692,0,0

In [9]:
target_var = 'prefarea'
dataset[target_var].value_counts()

prefarea
0    417
1    128
Name: count, dtype: int64

In [10]:
X = dataset.drop(columns=target_var)
y = dataset[target_var]

X.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,furnishingstatus
0,4.566365,1.046726,1.403419,1.421812,1.378217,1,0,0,0,1,1.517692,0
1,4.004484,1.757010,1.403419,5.405809,2.532024,1,0,0,0,1,2.679409,0
2,4.004484,2.218232,0.047278,1.421812,0.224410,1,0,1,0,0,1.517692,1
3,3.985755,1.083624,1.403419,1.421812,0.224410,1,0,1,0,1,2.679409,0
4,3.554979,1.046726,1.403419,-0.570187,0.224410,1,1,1,0,1,1.517692,0

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
y_train.value_counts()

prefarea
0    334
1    102
Name: count, dtype: int64

In [16]:
!pip install imblearn

WARNING: Ignoring invalid distribution -lotly (e:\pycharmprojects\venv_manager\.venv\lib\site-packages)
WARNING: Ignoring invalid distribution -lotly (e:\pycharmprojects\venv_manager\.venv\lib\site-packages)
WARNING: Ignoring invalid distribution -lotly (e:\pycharmprojects\venv_manager\.venv\lib\site-packages)

Collecting imblearn
  Using cached imblearn-0.0-py2.py3-none-any.whl.metadata (355 bytes)
Collecting imbalanced-learn (from imblearn)
  Downloading imbalanced_learn-0.14.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: numpy<3,>=1.25.2 in e:\pycharmprojects\venv_manager\.venv\lib\site-packages (from imbalanced-learn->imblearn) (1.26.3)
Requirement already satisfied: scipy<2,>=1.11.4 in e:\pycharmprojects\venv_manager\.venv\lib\site-packages (from imbalanced-learn->imblearn) (1.15.2)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in e:\pycharmprojects\venv_manager\.venv\lib\site-packages (from imbalanced-learn->imblearn) (1.5.1)
Requirement already satisfied: joblib<2,>=1.2.0 in e:\pycharmprojects\venv_manager\.venv\lib\site-packages (from imbalanced-learn->imblearn) (1.4.2)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in e:\pycharmprojects\venv_manager\.venv\lib\site-packages (from imbalanced-learn->imblearn) (3.5.0)
Using cached imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Downloading imbalanced_learn-0.14.0-py3-none-any.whl (239 kB)
Installing collected packages: imbalanced-learn, imblearn

   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 2/2 [imblearn]

Successfully installed imbalanced-learn-0.14.0 imblearn-0.0

In [18]:
from imblearn.over_sampling import SMOTE

smote = SMOTE()
X_train, y_train = smote.fit_resample(X_train, y_train)

print(y_train.value_counts())

prefarea
0    334
1    334
Name: count, dtype: int64

# Model

### Decision Tree

In [20]:
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [21]:
y_pred = decision_tree.predict(X_test)
print(y_pred)

[0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0
 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0
 0 0 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1]

In [25]:
from sklearn.metrics import accuracy_score, classification_report

accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.6330275229357798

### K-Nearest Neighbor

In [27]:
"""
example 1 (e1) = [2, 3]
example 2 (e2)
example 3 (e3)
...
example n  (en)

example (e) = [1, 1]

distance(e1, e) = sqrt((2-1)^2+(3-1)^2) = 0.258
distance(e2, e) = sqrt((2-1)^2+(3-1)^2) = 0.356
distance(e3, e) = sqrt((2-1)^2+(3-1)^2) = 0.197
distance(e4, e) = sqrt((2-1)^2+(3-1)^2) = 0.274

k = 3, Closest to e: e1 (1), e3(1), e4(0) prediction = e (1)
""";

In [28]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier()
knn_model.fit(X_train, y_train)
y_pred = knn_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
print(accuracy)
print(report)

0.6330275229357798
              precision    recall  f1-score   support

           0       0.88      0.60      0.71        83
           1       0.37      0.73      0.49        26

    accuracy                           0.63       109
   macro avg       0.62      0.67      0.60       109
weighted avg       0.76      0.63      0.66       109

In [ ]:
"""
Part 1: T means correct prediction, F means incorrect prediction
Part 2: What is the predicted class
TP: 25 
TN: 20
FP: 10 (F mean incorrect prediction, P means predicted class is Positive)
FN: 45

Accuracy = (TP + TN) / (TP + TN + FP + FN)
Precision = TP / (TP + FP)
Recall = TP / (TP + FN)
F1 = 2TP / (2TP + FP + FN)

(TP + FP) = Total number of predicted positive class
(TP + FN) = Total number of actual positive class
"""

### Support Vector Classifier

In [29]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

""" Initialize model """
svm_model = SVC(probability=True, random_state=42)

""" Train the model """
svm_model.fit(X_train, y_train)

""" Classify the instances """
y_pred = svm_model.predict(X_test)

""" Evaluate the models' performance """
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

""" Print accuracy and classification report """
print(f"SVM Classifier Accuracy: {accuracy}")
print("Classification Report:\n", report)

SVM Classifier Accuracy: 0.6880733944954128
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.75      0.78        83
           1       0.38      0.50      0.43        26

    accuracy                           0.69       109
   macro avg       0.60      0.62      0.61       109
weighted avg       0.72      0.69      0.70       109

# Ensemble

In [30]:
""" Boosting
Boosting => Models are trained sequentially

Suppose, 
decision_1.fit(X_train, y_train)
decision_2.fit(incorrect_predicted_rows)
decision_3.fit(incorrect_predicted_rows)
"""


from sklearn.ensemble import AdaBoostClassifier

""" Initialize model """
boosting_model = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(), 
    n_estimators=3, 
    random_state=42
)

""" Train the model """
boosting_model.fit(X_train, y_train)

""" Classify the instances """
y_pred = boosting_model.predict(X_test)

""" Evaluate the models' performance """
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

""" Print accuracy and classification report """
print(f"Boosting Classifier Accuracy: {accuracy}")
print("Classification Report:\n", report)

Boosting Classifier Accuracy: 0.7431192660550459
Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.82      0.83        83
           1       0.46      0.50      0.48        26

    accuracy                           0.74       109
   macro avg       0.65      0.66      0.66       109
weighted avg       0.75      0.74      0.75       109

E:\PyCharmProjects\venv_manager\.venv\lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

In [38]:
""" Bagging 
Models are learned individually
single decision tree: accuracy: 71%

X_train
y_train

multiple decision tree:
   decision_tree_1.fit(X_train_1, y_train_1)
   decision_tree_2.fit(X_train_2, y_train_2)
   ...
   decision_tree_N.fit(X_train_N, y_train_N)
   
   predict(x):
      y_pred_1 = decision_tree_1.predict(x)
      y_pred_2 = decision_tree_2.predict(x)
      ...
      
      return the majority prediction
"""


from sklearn.ensemble import BaggingClassifier

""" Initialize model """
bagging_model = BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=10, random_state=42)

""" Train the model """
bagging_model.fit(X_train, y_train)

""" Classify the instances """
y_pred = bagging_model.predict(X_test)

""" Evaluate the models' performance """
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

""" Print accuracy and classification report """
print(f"Bagging Classifier Accuracy: {accuracy}")
print("Classification Report:\n", report)

Bagging Classifier Accuracy: 0.7706422018348624
Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.90      0.86        83
           1       0.53      0.35      0.42        26

    accuracy                           0.77       109
   macro avg       0.67      0.62      0.64       109
weighted avg       0.75      0.77      0.75       109

In [32]:
"""
Stacking is an ensemble learning technique that combines predictions from multiple base models (of different types) to improve performance.
"""
from sklearn.ensemble import StackingClassifier, RandomForestClassifier

estimators = [
    ('decision_tree', DecisionTreeClassifier()), 
    ('knn', KNeighborsClassifier()), 
    ('svm', SVC(probability=True, random_state=42))
]

""" Initialize model """
stacking_model = StackingClassifier(estimators=estimators, final_estimator=RandomForestClassifier())

""" Train the model """
stacking_model.fit(X_train, y_train)

""" Classify the instances """
y_pred = stacking_model.predict(X_test)

""" Evaluate the models' performance """
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

""" Print accuracy and classification report """
print(f"Bagging Classifier Accuracy: {accuracy}")
print("Classification Report:\n", report)

Bagging Classifier Accuracy: 0.7431192660550459
Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.81      0.83        83
           1       0.47      0.54      0.50        26

    accuracy                           0.74       109
   macro avg       0.66      0.67      0.66       109
weighted avg       0.76      0.74      0.75       109

In [33]:
""" Voting """

from sklearn.ensemble import VotingClassifier

""" Initialize model """

voting_model = VotingClassifier(
    estimators=[
        ('decision_tree', DecisionTreeClassifier()), 
        ('knn', KNeighborsClassifier()), 
        ('svm', SVC(probability=True))],
    voting='soft'  # Use 'hard' for majority voting
)

""" Train the model """
voting_model.fit(X_train, y_train)

""" Classify the instances """
y_pred = voting_model.predict(X_test)

""" Evaluate the models' performance """
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

""" Print accuracy and classification report """
print(f"Voting Classifier Accuracy: {accuracy}")
print("Classification Report:\n", report)

Voting Classifier Accuracy: 0.7522935779816514
Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.83      0.84        83
           1       0.48      0.50      0.49        26

    accuracy                           0.75       109
   macro avg       0.66      0.67      0.66       109
weighted avg       0.76      0.75      0.75       109